def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Use it to require both react-native's and this package's scripts:
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '15.0'
prepare_react_native_project!

# Setup permissions for react-native-permissions
setup_permissions([
  'Camera',
])
 
# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
# Disable Flipper to avoid module conflicts with fmt and folly
flipper_config = FlipperConfiguration.disabled
 
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Enable modular headers for Swift pods
use_modular_headers!

target 'SolidiMobileApp4' do
  use_modular_headers!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Disable Hermes engine to avoid dSYM issues
    :hermes_enabled => false,
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'RNFS', :path => '../node_modules/react-native-fs'


  target 'SolidiMobileApp4Tests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Fix Braintree deprecation warnings
    installer.pods_project.targets.each do |target|
      if target.name == 'Braintree'
        target.build_configurations.each do |config|
          config.build_settings['WARNING_CFLAGS'] ||= []
          config.build_settings['WARNING_CFLAGS'] << '-Wno-deprecated-declarations'
        end
      end
      
      # Fix Hermes dSYM generation for archiving
      if target.name == 'hermes-engine'
        target.build_configurations.each do |config|
          config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
      end
    end
  end
end
