#!/bin/bash

# APNS Certificate Creation Helper
# This script guides you through creating the APNS certificate

echo "======================================"
echo "APNS Certificate Setup Guide"
echo "======================================"
echo ""
echo "Follow these steps:"
echo ""
echo "STEP 1: Create App ID"
echo "---------------------"
echo "1. Open: https://developer.apple.com/account/resources/identifiers/list"
echo "2. Click the '+' button"
echo "3. Select 'App IDs' → Continue"
echo "4. Description: Solidi Mobile App"
echo "5. Bundle ID: co.solidi.mobile.test (Explicit)"
echo "6. Capabilities: Check 'Push Notifications'"
echo "7. Click Continue → Register"
echo ""
read -p "Press ENTER when App ID is created..."
echo ""

echo "STEP 2: Create Certificate Signing Request (CSR)"
echo "------------------------------------------------"
echo "1. Open Keychain Access app"
echo "2. Menu: Keychain Access → Certificate Assistant → Request a Certificate from a Certificate Authority"
echo "3. User Email Address: (your email)"
echo "4. Common Name: Solidi APNS Dev"
echo "5. Request is: Saved to disk"
echo "6. Save to: ~/Desktop/CertificateSigningRequest.certSigningRequest"
echo "7. Click Continue"
echo ""
read -p "Press ENTER when CSR is created..."
echo ""

echo "STEP 3: Create APNS Certificate"
echo "-------------------------------"
echo "1. Back in Apple Developer Portal"
echo "2. Find your App ID 'Solidi Mobile App'"
echo "3. Click on it → Configure (under Push Notifications)"
echo "4. Development SSL Certificate → 'Create Certificate'"
echo "5. Upload the CSR file from ~/Desktop"
echo "6. Download the certificate (aps_development.cer)"
echo "7. Save to ~/Desktop/aps_development.cer"
echo "8. Double-click to install in Keychain"
echo ""
read -p "Press ENTER when certificate is installed in Keychain..."
echo ""

echo "STEP 4: Export as .p12"
echo "----------------------"
echo "1. Open Keychain Access"
echo "2. In 'login' keychain, find:"
echo "   'Apple Development iOS Push Services: co.solidi.mobile.test'"
echo "3. Right-click → Export 'Apple Development iOS Push Services...'"
echo "4. File Format: Personal Information Exchange (.p12)"
echo "5. Save as: ~/Desktop/apns_dev_cert.p12"
echo "6. Password: (create a strong password)"
echo "7. Click Save"
echo "8. Enter your Mac password if prompted"
echo ""
read -p "Press ENTER when .p12 file is exported..."
echo ""

# Verify file exists
if [ -f ~/Desktop/apns_dev_cert.p12 ]; then
    echo "✅ SUCCESS! APNS certificate created at:"
    echo "   ~/Desktop/apns_dev_cert.p12"
    echo ""
    echo "Next step: Create AWS SNS Platform Application"
    echo "Run: ./scripts/setup-aws-sns.sh"
else
    echo "❌ ERROR: apns_dev_cert.p12 not found"
    echo "Please make sure you exported the certificate correctly"
fi
