AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Solidi Push Notification API with DynamoDB storage

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

  PlatformApplicationArnIOS:
    Type: String
    Description: ARN of the SNS Platform Application for iOS
    Default: ""

  PlatformApplicationArnAndroid:
    Type: String
    Description: ARN of the SNS Platform Application for Android
    Default: ""

Resources:
  # DynamoDB Tables
  DevicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub solidi-devices-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: deviceId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: deviceId
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: Solidi

  NotificationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub solidi-notifications-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: Solidi

  # Lambda Functions
  RegisterDeviceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub solidi-register-device-${Environment}
      CodeUri: register-device/
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          DEVICES_TABLE: !Ref DevicesTable
          PLATFORM_APPLICATION_ARN_IOS: !Ref PlatformApplicationArnIOS
          PLATFORM_APPLICATION_ARN_ANDROID: !Ref PlatformApplicationArnAndroid
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DevicesTable
        - SNSPublishMessagePolicy:
            TopicName: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:CreatePlatformEndpoint
                - sns:DeleteEndpoint
                - sns:GetEndpointAttributes
                - sns:SetEndpointAttributes
              Resource: '*'
      Events:
        RegisterDeviceApi:
          Type: Api
          Properties:
            Path: /register
            Method: POST
            RestApiId: !Ref SolidiApi

  SendNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub solidi-send-notification-${Environment}
      CodeUri: send-notification/
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          DEVICES_TABLE: !Ref DevicesTable
          NOTIFICATIONS_TABLE: !Ref NotificationsTable
          PLATFORM_APPLICATION_ARN_IOS: !Ref PlatformApplicationArnIOS
          PLATFORM_APPLICATION_ARN_ANDROID: !Ref PlatformApplicationArnAndroid
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DevicesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref NotificationsTable
        - SNSPublishMessagePolicy:
            TopicName: '*'
      Events:
        SendNotificationApi:
          Type: Api
          Properties:
            Path: /send
            Method: POST
            RestApiId: !Ref SolidiApi

  GetNotificationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub solidi-get-notifications-${Environment}
      CodeUri: get-notifications/
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          NOTIFICATIONS_TABLE: !Ref NotificationsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref NotificationsTable
      Events:
        GetNotificationsApi:
          Type: Api
          Properties:
            Path: /notifications
            Method: GET
            RestApiId: !Ref SolidiApi

  # API Gateway
  SolidiApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub solidi-push-api-${Environment}
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${SolidiApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub ${AWS::StackName}-ApiUrl

  DevicesTableName:
    Description: DynamoDB Devices Table Name
    Value: !Ref DevicesTable
    Export:
      Name: !Sub ${AWS::StackName}-DevicesTable

  NotificationsTableName:
    Description: DynamoDB Notifications Table Name
    Value: !Ref NotificationsTable
    Export:
      Name: !Sub ${AWS::StackName}-NotificationsTable

  RegisterDeviceFunctionArn:
    Description: Register Device Lambda Function ARN
    Value: !GetAtt RegisterDeviceFunction.Arn

  SendNotificationFunctionArn:
    Description: Send Notification Lambda Function ARN
    Value: !GetAtt SendNotificationFunction.Arn

  GetNotificationsFunctionArn:
    Description: Get Notifications Lambda Function ARN
    Value: !GetAtt GetNotificationsFunction.Arn
